# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The blog of Lea
description: 'This is a blog to show what I bake' # write a nice description for your blog
baseurl: '/lea-blog' # the subpath of your site, e.g. /blog
url: 'https://jbquelen.github.io' # the base hostname & protocol for your site http://www.example.com
# google_analytics: 'UA-XXXXXX-X'
twitter_username: 'twitter_username'

# Build settings
markdown: kramdown

permalink: '/:title/'

gems: [jekyll-paginate]

paginate: 10
